### ISSUE TITLE
Vendor CA certificates

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/raven-go#103]
This way raven does not rely on system level OS certificates to be installed.

Should be easy to just vendor in https://github.com/certifi/gocertifi

**Comment by dolmen** [comment]
It would be better it Sentry would maintain its own more restricted list of trusted root CA certificates (in a separate repo, for all clients not just Go) and raven-go would embed that list (using generated code with a "go generate" task).

**Comment by dolmen** [comment]
I just noticed that [you are starting to be involved into `gocertifi`](https://github.com/certifi/gocertifi/pull/10).
I think it would be better to have the `go generate` task in `raven-go` itself, with a limited set of root certificates blessed by Sentry.

**Comment by mattrobenolt** [comment]
Unfortunately, I can’t really do that. Lots of people run their own Sentry servers, so it’s not reasonable for us to just embed certificates for sentry.io alone. We need basically any normal trusted certificates.

**Comment by jmkim** [comment]
> This way raven does not rely on system level OS certificates to be installed.

> We need basically any normal trusted certificates.

Hi @mattrobenolt, is there a reason to use `gocerifi` instead of OS certificates? just asking.

**Comment by mattrobenolt** [comment]
There was at the time. I'd like to split it out and just make it easier to customize them yourself with instructions on how to use gocertifi when you need it.

The primary reasons were:
 * We vendor the Mozilla trusted cert bundle in raven-python (same bundle that comes from Certifi)
 * It was pretty common to run Go binaries out of minimal Docker containers that don't have OS level root certificates. So even in cases where your application might need them, reporting to Sentry would be broken since _we_ needed them. So in this case it made sense to me to bundle in a scenario where it always works.

**Comment by dolmen** [comment]
I just made a PR on gocertifi to ease the task of vendoring/forking gocertifi with a different set of certificates: https://github.com/certifi/gocertifi/pull/17

But I still think that using gocertifi for Raven is a bad idea.
