### ISSUE TITLE
No SetExtraContext function?

### ISSUE THREAD

**Issue by goofansu** [getsentry/raven-go#111]
How can I set extra content described in https://docs.sentry.io/learn/context/#extra-context ?

**Comment by adriancooney** [comment]
You can't, it's hard coded: https://github.com/getsentry/raven-go/blob/master/client.go#L163-L175

```go
// NewPacket constructs a packet with the specified message and interfaces.
func NewPacket(message string, interfaces ...Interface) *Packet {
	extra := map[string]interface{}{
		"runtime.Version":      runtime.Version(),
		"runtime.NumCPU":       runtime.NumCPU(),
		"runtime.GOMAXPROCS":   runtime.GOMAXPROCS(0), // 0 just returns the current value
		"runtime.NumGoroutine": runtime.NumGoroutine(),
	}
	return &Packet{
		Message:    message,
		Interfaces: interfaces,
		Extra:      extra,
	}
}
```

I'd like this feature too. For now, we're sending the variable data as tags which isn't actually ideal.

**Comment by syndbg** [comment]
Update on this,

https://github.com/getsentry/raven-go/issues/111 addresses this.
