### ISSUE TITLE
Support chained errors

### ISSUE THREAD

**Issue by lumost** [getsentry/raven-go#120]
The full Sentry API supports chained Exceptions https://docs.sentry.io/clientdev/interfaces/exception/ however it appears that the go client de-duplicates all interfaces based on Class() over [here](https://github.com/getsentry/raven-go/blob/master/client.go#L248)

Would it be possible to allow a special case on interface type to send a list of errors?

**Comment by 0x4445565A** [comment]
It wouldn't be a special case you simply have to implement the interface, which means create a struct (with json tags) that has a method Class() 

You could probably hack up my solution for Breadcrumbs and do something similar
https://github.com/getsentry/raven-go/issues/118#issuecomment-273364662
