### ISSUE TITLE
No way to send custom extra data

### ISSUE THREAD

**Issue by akrylysov** [getsentry/raven-go#125]
Python client provides a way to send custom extra data `client.captureMessage('message', extra={'foo': 'bar'})`, but Go client doesn't.

**Comment by nsf** [comment]
+1. Add "extra" interface, please, or what choice do I have, but to use tags for passing down internal unique message IDs. Which is definitely a not kind of info to be indexed.

**Comment by triamazikamno** [comment]
You can get around it by writing your own CaptureMessage function. I got around it with something like this in my util package:
```go
type Ctx map[string]interface{}

func SentryCaptureMessage(message string, ctx *Ctx) {
	packet := &raven.Packet{
		Message: message,
		Interfaces: []raven.Interface{
			&raven.Message{
				Message: message,
				Params:  nil,
			},
		},
		Extra: *ctx,
	}
	raven.Capture(packet, nil)
}
```

And in my code I use it like this:
```go
util.SentryCaptureMessage("Some error message", &util.Ctx{"variable 1": var1, "variable 2": var2})
```

And now var1 and var2 appear in "Additional data" section

**Comment by zkanda** [comment]
This is probably what your looking for: https://docs.sentry.io/clients/go/#additional-context

**Comment by syndbg** [comment]
@zkanda There's a difference though. In the Go client you pass tags there (ref: https://github.com/getsentry/raven-go/blob/8f3acaed05e4fbfc6c321d371fdc05493e07d31e/client.go#L610)

while in the Python client you can pass both `tags` and `extra` (ref: https://github.com/getsentry/raven-python/blob/869561b0d38f0e23b0c19924fe58a802ad0a3af7/raven/base.py#L568)

**Comment by zkanda** [comment]
Ahh indeed, there's actually extra but it's not exposed: https://github.com/getsentry/raven-go/blob/8f3acaed05e4fbfc6c321d371fdc05493e07d31e/client.go#L158 Can someone send a PR on that one? Thanks for looking into it.

**Comment by syndbg** [comment]
@zkanda On it.

**Comment by jpatters** [comment]
I agree that this should be a feature, but I thought I would offer a work around until the PR is merged.

If your additional data is json marshalable you can implement `Interface` (https://godoc.org/github.com/getsentry/raven-go#Interface) and pass it as the third param to `CaptureError` (or most of the others) like so:

When implementing `Interface` make sure that `Class() string` returns `extra` and it will show up in the additional data section.

**Comment by xevix** [comment]
For the next person stumbling on this, concretely the workaround by @jpatters works like this:

```go
type Foo struct {
    MyVal string `json:"myval"`
}

// Implements raven.Interface, and raven-go will then shove the JSONified struct into "extra"
func (f *Foo) Class() string {
    return "extra"
}
```

**Comment by MickaelBergem** [comment]
For the next person stumbling on this, you can now use the following snippet:

```golang
raven.CaptureError(
    raven.WrapWithExtra(err, map[string]interface{}{
        "extra1": "my-extra-data",
        "extra2": 1234,
    }),
    map[string]string{"tag1": "tag"})
```

**Comment by rkuska** [comment]
It seems like `raven.CapturePanic` doesn't provide a way how to specify some extras as they are created with some default values in `raven.NewPacket`.

**Comment by kamilogorek** [comment]
As the original issue is resolved, I'll close this one and create new one for Panics – https://github.com/getsentry/raven-go/issues/235
