### ISSUE TITLE
stacktrace.go: fileContext should cache "file does not exist"?

### ISSUE THREAD

**Issue by evanj** [getsentry/raven-go#128]
If the source files do not exist, or are not in the right path, every call to NewStacktrace causes an attempt to open and read the file. This causes wasted system calls and memory allocations on long running servers that are deployed without their source code.

The cause is that in `stacktrace.go` the function `fileContext` caches the lines of source files. However, if the file does not exist, it does nothing. My suggestion: it should also cache "file does not exist", and not try to open a file more than once.

The disadvantage to caching: a user will need to restart their binary for it to pick up the source files, if they initially run into errors and don't have the files in place.

#### Additional Context

I'm indirectly using `raven-go` since I use Stripe's Veneur server (https://github.com/stripe/veneur). I noticed while investigating an unrelated problem, that every time an error was occurring it would attempt to open the source code files, which I don't ship on our production machines. We were running into an error regularly, so this showed up in a profile I was looking at. I'm going to use the following workarounds:

* Make the context configurable, and use `0` in production.
* Don't log so many errors

**Comment by mattrobenolt** [comment]
Boom, I like it. I can either poke at this, or you can submit a PR if you beat me to it, but again, I find this a reasonable request. I don't think we need to handle the case of someone putting source files into place, while the binary is running, and expecting it to magically work. If we do care about that, we can cache the misses with a TTL and do a check, say, once per minute or something.

**Comment by evanj** [comment]
Fixed by b68337dbf03e7fbb53d9fd9b63fd09b28e8f13f7
