### ISSUE TITLE
Client.Capture: Should return a closed chan, not a nil chan

### ISSUE THREAD

**Issue by evanj** [getsentry/raven-go#129]
Stripe Veneur has code like the following to ensure that in the case of fatal errors, sentry receives the message:

```go
	_, ch := ravenClient.Capture(&p, nil)

	if e.Level == logrus.PanicLevel || e.Level == logrus.FatalLevel {
		// we don't want the program to terminate before reporting to sentry
		return <-ch
	}
```

If Sentry is not configured, Veneur relies on the fact that "It is a no-op when client is nil." (from the Capture API doc). Unfortunately, the implementation returns a `nil` channel. Reading from a `nil` channel blocks forever. This hangs the server when it is trying to crash. Instead, Capture should return a *closed* channel, which will always return nil.

As a workaround, I'm modifying Veneur to not call the Client.Capture if the client is nil.

**Comment by mattrobenolt** [comment]
I think this is reasonable. Would you like to submit a PR to handle this?

**Comment by evanj** [comment]
Yes, I can make an attempt tomorrow. Thanks!
