### ISSUE TITLE
Weird behavior with on-demand sentry and Golang CaptureError

### ISSUE THREAD

**Issue by kwiesmueller** [getsentry/raven-go#142]
I tried to use Sentry On-Demand this day and was adding the raven lib to a new project for this... The setup is up so far and sentry seams to work well. I tested it with sending some packages from the bash etc...
But when using raven-go with this particular project on this instance I get weird behavior in forms of event tracking.

As an example, this should create an error in sentry:
```
var sentryDSN = "xxx"
func main() {
	raven.SetDSN(sentryDSN)
	terr := errors.New("it works")
	CheckError(terr)
}
func CheckError(e error) {
	eventID := raven.CaptureError(e, nil)
	fmt.Println(eventID)
}
```
But when fired it does send an eventID to the console but no event appears in sentry.
I did a few hours of debugging and analyzing... When using the example from here: https://github.com/getsentry/raven-go/blob/master/example/example.go
and manually creating the package it kinda works... But only using &raven.Packet{} and not using raven.NewPacket() ... Seamed random for me and it was... After a few tries with no obvious changes it seamed to work now.

But still, raven.CaptureError did not create new events at sentry, why?
I found that there is no way of figuring out whether or not the CaptureError was successful and now the black magic begins:

Recap -> No changes to Sentry and this does not create any events:
```
eventID := raven.CaptureError(e, nil)
	fmt.Println(eventID)
``` 
After changing the sentry code to include an error or at least check the error from the embedded Capture call:
```
func (client *Client) CaptureError(err error, tags map[string]string, interfaces ...Interface) string {
	if client == nil {
		return ""
	}

	if client.shouldExcludeErr(err.Error()) {
		return ""
	}

	packet := NewPacket(err.Error(), append(append(interfaces, client.context.interfaces()...), NewException(err, NewStacktrace(1, 3, client.includePaths)))...)
	eventID, ch := client.Capture(packet, tags)
	if e := <-ch; e != nil {
		panic(e)
	}
	return eventID
}
```
oh wonder... I get an event in sentry...
Fire some time, get events instantly and then I removed the snippet again -> No Events anymore...
How could this be? And how is it possible that another project using the exact same call onto the same DSN does create events without any changes to sentry?

I am confused and got no idea on where to search for the issue.

**Comment by kwiesmueller** [comment]
Oh damn, my change makes it a CaptureAndWait right?
This means, that when not doing a wait so close to the app exit (due to errors) it won't be sent as the main proc exits before it is able to finish?

**Comment by mattrobenolt** [comment]
I think you have it figured out. :) Your process is most certainly exiting before being sent, so you need to either listen to the channel and wait explicitly, or use the convenience CaptureAndWait so it blocks until done.

I would only suggest using CaptureAndWait in a CLI tool or in some other short lived process. In a normal long lived, web application or something like that, just use the normal methods so you don’t block.

**Comment by rikuayanokozy** [comment]
Maybe we could make Client.Close looks like:
```go
func (client *Client) Close() {
  close(client.queue)
  waitCh := make(chan struct{})
  go func() {
    client.wg.Wait()
    waitCh <- struct{}{}
  }()
  select {
  case <-time.NewTimer(SEND_TIMEOUT):
  case <-waitCh:
  }
}
```

That would be helpful if we want to send all errors in the signal handler.
