### ISSUE TITLE
Error not being logged to Sentry.

### ISSUE THREAD

**Issue by jeffreyyong** [getsentry/raven-go#149]
```
	raven.SetDSN("******")

	raven.CapturePanic(func() {
		_, err := os.Open("non-existent-file")

		if err != nil {
			log.Fatal("panic string")
			panic("panic string")
		}
	}, nil)
```

I put the right DSN for sentry and I try to open a non-existent file to force the error to happen. I am wondering why nothing is being logged to my sentry account?

**Comment by mattrobenolt** [comment]
Is your program exiting before it is delivered? Try using `CapturePanicAndWait`

**Comment by jeffreyyong** [comment]
I tried using `CapturePanicAndWait` method but it's still not working. I will try again
