### ISSUE TITLE
store and forward

### ISSUE THREAD

**Issue by gedw99** [getsentry/raven-go#170]
I am using Sentry in an environment behind corporate VPN and so i need to do a store and forward pattern for the crash reports.

This would mean that the analytics and saved to disk, and then i need to forward them out to your system.  
SO, is there a way to set the raven-go package to send the data to disk or other ?

**Comment by mattrobenolt** [comment]
Not built in, but in theory, you could just write a different `Transport` that writes to disk. https://github.com/getsentry/raven-go/blob/master/client.go#L83

Then plug this into `Client.Transport‘.
