### ISSUE TITLE
Unable to change level tag

### ISSUE THREAD

**Issue by fosini** [getsentry/raven-go#179]
Hello.
Everything works fine, except changing the level tag. Once the level tag has been set, my message simply does not get delivered. 

```
 tagsMap := make(map[string]string)
	tagsMap["level"] = "info"
	raven.CaptureMessageAndWait("This is an info.", tagsMap)

```
I just don't want this message to be delivered as an error.
It is very urgent so please help me, else I am forced to change my logging platform.

**Comment by kamilogorek** [comment]
Moved to https://github.com/getsentry/raven-go/issues/237
