### ISSUE TITLE
Wrong doc for method CapturePanicAndWait

### ISSUE THREAD

**Issue by bwowk** [getsentry/raven-go#180]
https://github.com/getsentry/raven-go/blob/7562301a6763c9ac631b0a2011b4aa0e064e45d4/client.go#L763

I Belive this was meant to say ` CapturePanicAndWait is identical to CapturePanic [...]`

same thing on https://github.com/getsentry/raven-go/blob/7562301a6763c9ac631b0a2011b4aa0e064e45d4/client.go#L799

**Comment by kamilogorek** [comment]
Fixed
