### ISSUE TITLE
missing ServeHTTP method

### ISSUE THREAD

**Issue by algogrit** [getsentry/raven-go#182]
cannot use ravenHandler (type func(http.ResponseWriter, *http.Request)) as type http.Handler in argument to n.UseHandler:
	func(http.ResponseWriter, *http.Request) does not implement http.Handler (missing ServeHTTP method)

I am wrapping the http.HandlerFunc using raven.RecoveryHandler; when trying to use with Negroni.

**Comment by gauravagarwalr** [comment]
Perhaps changing the signature from:

`func RecoveryHandler(handler func(http.ResponseWriter, *http.Request)) func(http.ResponseWriter, *http.Request)`

to

`func RecoveryHandler(handler http.HandlerFunc) http.HandlerFunc`

might help?
