### ISSUE TITLE
CaptureError to support Level.Info

### ISSUE THREAD

**Issue by pzhao5** [getsentry/raven-go#198]
No all error are considered as Error, Some could be just Info. Allow a way for us to set Level as Info in CaptureError method

**Comment by kamilogorek** [comment]
It's already doable through manual `Packet` creation - https://github.com/getsentry/raven-go/issues/79#issuecomment-458933980
We'll rethink how events can be created in a slightly more flexible way though.

**Comment by kamilogorek** [comment]
Moved to https://github.com/getsentry/raven-go/issues/237
