### ISSUE TITLE
Golang errors not reaching Sentry8 servers

### ISSUE THREAD

**Issue by alok87** [getsentry/raven-go#200]
We have a very simple script to check if the log reaches sentry8 server.
It is not happening.

```go
package main

import (
	"log"
	"os"

	"github.com/getsentry/raven-go"
)

func init() {
	raven.SetDSN("https:/XXX")
}

func main() {
	_, err := os.Open("filename.ext")
	if err != nil {
		raven.CaptureError(err, nil)
		log.Panic(err)
	}
}
```

We are using the latest raven package: ed7bcb39ff10f39ab08e317ce16df282845852fa

Please suggest.

**Comment by mattrobenolt** [comment]
In this case, your program is exiting before it is sent. 

You’d need to use `raven.CaptureErrorAndWait` here.

**Comment by alok87** [comment]
@mattrobenolt The issue happened with `CaptureErrorAndWait` also. The problem was the request was reaching Sentry8 but our queue was stuck because one app was spamming it :)
Thank you
