### ISSUE TITLE
error in stacktrace.go

### ISSUE THREAD

**Issue by behzadsh** [getsentry/raven-go#225]
I get this error when I try to build my code
```
../../getsentry/raven-go/stacktrace.go:62:17: cannot convert f (type "github.com/pkg/errors".Frame) to type uintptr
```

**Comment by runcom** [comment]
same here

**Comment by ManouchehrRasoulli** [comment]
hi i resolve this problem its pretty simple :+1: 
open op the 
../../getsentry/raven-go/stacktrace.go
file
get into line 61
and replace with this code
>> for f, _ := range stacktracer.StackTrace()

**Comment by ManouchehrRasoulli** [comment]
i haven't this error

**Comment by loeffel-io** [comment]
@ManouchehrRasoulli done in PR #226
