### ISSUE TITLE
Sending multiple exceptions at once

### ISSUE THREAD

**Issue by pzduniak** [getsentry/raven-go#48]
Is it possible to send multiple exceptions at once? I've tried creating a packet and then appending lots of "raven.Exception" structs to the .Interfaces field but only one exception ends up showing in Sentry. Am I doing it incorrectly?

**Comment by pzduniak** [comment]
https://github.com/lavab/lavatrace/blob/master/api/main.go#L126-L284
The code which I can't get to work.

**Comment by tylrtrmbl** [comment]
Only a single Exception can be captured at a time. To accomplish what you're trying to do, make a new Packet for each entry and capture each one individually. Be aware of the rate limiting / sampling mechanism on Sentry if you do!
