### ISSUE TITLE
Timestamp produces an error

### ISSUE THREAD

**Issue by derailed** [getsentry/raven-go#60]
Hi,

   Thanks for contributing this lib! Having issues logging events on sentry. It looks like the default timestamp on packets is not what sentry is expecting hence creating an error on every events.

There was 1 error encountered while processing this event.
Discarded invalid value for parameter 'timestamp' Collapse
{
  "name": "timestamp",
  "value": "2015-09-30T18:22:28Z"
}

Can't seem to locate the api docs to figure out what shape the timestamp should be??

**Comment by mattrobenolt** [comment]
Hmm, that's odd, was this with getsentry.com?

**Comment by mattrobenolt** [comment]
So looking at the code, we will reject a timestamp that's in the future or too far in the past.

Is it possible that your clock is skewed? If this is on getsentry.com, I can take a look at what you sent and see.

**Comment by derailed** [comment]
Hi Matt,

   Yes this is the error on the sentry site. Looking at your code you fetch
the utc timestamp and add it to the packet by default and send it as a
string. Somehow sentry is not liking the tag but can't find this anywhere
in the docs what is expected here...

-Fernand

**Comment by mattrobenolt** [comment]
Yeah, the format of the timestamp is correct. My current guess is that it's from clock skew since we'll reject a timestamp if it appears in the future.

Can you link me to the error on getsentry.com? Feel free to send it to support@getsentry.com and I'll look.

**Comment by derailed** [comment]
Thanks Matt! The lib is sending a utc timestamp. Is getsentry expecting utc
or local time?

**Comment by mattrobenolt** [comment]
UTC. Like I said, the library is sending the correct timestamp format.

I think the problem is your server clock is skewed from ours, so it thought the timestamp was in the future. If you send me a link, I'll take a look and see what the issue was. Without seeing what the entire event was, I can't investigate. :)

**Comment by derailed** [comment]
Hi Matt - pilot error indeed - double checked the time on the event and
you're absolutely correct. Tx for looking into this!

**Comment by mattrobenolt** [comment]
Awesome, thanks for hanging in there. :)
