### ISSUE TITLE
A simple example

### ISSUE THREAD

**Issue by mjdavies** [getsentry/raven-go#67]
Morning all

We're just starting on our Go journey, so please excuse the dumbass.

Do you have a very simple example of how to trigger a push to our sentry server using raven-go?

I'm on OSX 10.11.1, and running go1.5.1 darwin/amd64.

I've tried using some of the examples in this repo, and some I've found elsewhere, but I must be doing something fundamentally wrong as I just can't get it to push to sentry.

Any tips, or links, gratefully accepted.

**Comment by tylrtrmbl** [comment]
@mjdavies; can you post a code sample of your best attempt so far?

**Comment by mjdavies** [comment]
Hi Taylor

Thanks for getting back to me.

I've used https://github.com/getsentry/raven-go/blob/master/example/example.go as a starting point, and simply added my sentry details like so.

    package main
    
    import (
    	"errors"
    	"fmt"
    	"github.com/getsentry/raven-go"
    	"log"
    	"net/http"
    	"os"
    )
    
    func init() {
        raven.SetDSN("http://MYSENTRYDETAILS")
    }
    
    func trace() *raven.Stacktrace {
    	return raven.NewStacktrace(0, 2, nil)
    }
    
    func main() {
    	client, err := raven.NewWithTags(os.Args[1], map[string]string{"foo": "bar"})
    	if err != nil {
    		log.Fatal(err)
    	}
    	httpReq, _ := http.NewRequest("GET", "http://example.com/foo?bar=true", nil)
    	httpReq.RemoteAddr = "127.0.0.1:80"
    	httpReq.Header = http.Header{"Content-Type": {"text/html"}, "Content-Length": {"42"}}
    	packet := &raven.Packet{Message: "Test report", Interfaces: []raven.Interface{raven.NewException(errors.New("example"), trace()), raven.NewHttp(httpReq)}}
    	_, ch := client.Capture(packet, nil)
    	if err = <-ch; err != nil {
    		log.Fatal(err)
    	}
    	log.Print("sent packet successfully")
    }
    
    // CheckError sends error report to sentry and records event id and error name to the logs
    func CheckError(err error, r *http.Request) {
    	client, err := raven.NewWithTags(os.Args[1], map[string]string{"foo": "bar"})
    	if err != nil {
    		log.Fatal(err)
    	}
    	packet := raven.NewPacket(err.Error(), raven.NewException(err, trace()), raven.NewHttp(r))
    	eventID, _ := client.Capture(packet, nil)
    	message := fmt.Sprintf("Error event with id \"%s\" - %s", eventID, err.Error())
    	log.Println(message)
    }

When I then run go build, and go install, and then execute the example file, I get this.

    trj260-mdmac:example$ example
    panic: runtime error: index out of range
    
    goroutine 1 [running]:
    main.main()
    	/Users/mjdavies/go/src/github.com/uniglam/example/example.go:21 +0x9ce
    
    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
    	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
    
    goroutine 5 [chan receive]:
    github.com/getsentry/raven-go.(*Client).worker(0xc8200ac0b0)
    	/Users/mjdavies/go/src/github.com/getsentry/raven-go/client.go:417 +0x60
    created by github.com/getsentry/raven-go.newClient
    	/Users/mjdavies/go/src/github.com/getsentry/raven-go/client.go:306 +0x192

Like I said, I may be doing something really stupid.

**Comment by jackliu97** [comment]
you need to call it like so

```
go build && ./example http://MYSENTRYDETAILS
```

and take out the `init` function, you don't need that.

`NewWithTags` creates a new instance of client with the first arg being your dsn cred, so you need to pass it in as an arg when you run `example`

https://github.com/getsentry/raven-go/blob/1cc47a9463b90f246a0503d4c2e9a55c9459ced3/client.go#L319

**Comment by mjdavies** [comment]
Thanks Jack, that worked a treat!!
