### ISSUE TITLE
Methods do not check errors

### ISSUE THREAD

**Issue by EricLagergren** [getsentry/raven-go#80]
Ran into an issue today where an `Interface` type contained a channel, which Go can't marshal into JSON. Obviously this isn't valid, but it didn't occur to me I was marshaling that (my `Interface` was a larger, quite nested struct) until I ran into an index out of range error which was quite annoying to debug at first.

My suggestion: check the errors and let them bubble up the stack.

(Here's the offending code: https://github.com/getsentry/raven-go/blob/dffeb57df75d6a911f00232155194e43d79d38d7/client.go#L245)

Scanning through the library, there's a fair amount of other places where errors are swallowed.

**Comment by EricLagergren** [comment]
Curious if there's an update on this.

**Comment by mattrobenolt** [comment]
There is not, but if you are able to submit a pull request, I'd be happy to review. Otherwise, some code to reproduce the issue would make it simpler for me to fix.

**Comment by EricLagergren** [comment]
@mattrobenolt minimal repro: https://play.golang.org/p/7SxvL55pM_

Just swap in your own DSN and you'll get something like:

```
panic: runtime error: slice bounds out of range

goroutine 5 [running]:
panic(0x7d08c0, 0xc82000a0e0)
	/usr/lib/go/src/runtime/panic.go:481 +0x3e6
sermocrm.com/vendor/github.com/getsentry/raven-go.(*Packet).JSON(0xc8200bc600, 0x0, 0x0, 0x0)
	/home/eric/gopath/src/sermocrm.com/vendor/github.com/getsentry/raven-go/client.go:246 +0x3e4
sermocrm.com/vendor/github.com/getsentry/raven-go.serializedPacket(0xc8200bc600, 0x0, 0x0, 0x0, 0x0)
	/home/eric/gopath/src/sermocrm.com/vendor/github.com/getsentry/raven-go/client.go:684 +0x58
sermocrm.com/vendor/github.com/getsentry/raven-go.(*HTTPTransport).Send(0xc820015500, 0xc820015680, 0x2a, 0xc82007e580, 0x74, 0xc8200bc600, 0x0, 0x0)
	/home/eric/gopath/src/sermocrm.com/vendor/github.com/getsentry/raven-go/client.go:666 +0x6a
sermocrm.com/vendor/github.com/getsentry/raven-go.(*Client).worker(0xc8200be210)
	/home/eric/gopath/src/sermocrm.com/vendor/github.com/getsentry/raven-go/client.go:423 +0x166
created by sermocrm.com/vendor/github.com/getsentry/raven-go.newClient
	/home/eric/gopath/src/sermocrm.com/vendor/github.com/getsentry/raven-go/client.go:306 +0x193
exit status 2
```

**Comment by mattrobenolt** [comment]
Ah, ok, I see the issue. Not entire sure what we'll do here, but I'll come up with something.

Thanks. :)

**Comment by EricLagergren** [comment]
I'd return the error and let it bubble up somehow, but that might require a bit of an API change. Maybe.

Cheers :)

**Comment by mattrobenolt** [comment]
Yeah, and we don't do that elsewhere. In other clients, we'll discard unserializable items since we always want our capturing to succeed. I'll have to see if I can massage go to do that behavior.

**Comment by EricLagergren** [comment]
Super basic workaround would be to recover the panic and then send the panic on the channel `Capture` returns.

**Comment by mattrobenolt** [comment]
Yeah, I just don't think that's the right thing to do here. You shouldn't have to handle errors from the library that's intending to handle your errors. :) We could log the issue, but our goal is to carry on and make sure we can report whatever we can.

**Comment by EricLagergren** [comment]
True, but `Capture` does return a channel to so you can check the send's request, and an out of bounds panic is a failed request.

**Comment by viru** [comment]
Any update on this? We've just hit that problem too. I think error from marshalling should be returned all way up to `Send()` which already is capable of returning errors. I can create PR for that if you feel it's good solution, currently testing that fix in our env. Problem with it is that exported `JSON()` method would change (it would return an error), but I don't know if this method should be exported at all.

**Comment by viru** [comment]
Hi, not sure if it's correct solution, but we're using this patch in our system.
