### ISSUE TITLE
Cannot "override" the `packet.Level` when calling `CaptureMessage`

### ISSUE THREAD

**Issue by francoishill** [getsentry/raven-go#83]
It seams like there is no way to currently override the `packet.Level` when we call `CaptureMessage`. The call to `client.context.interfaces()` is also private so we cannot use the raw `client.Capture()` method to achieve the same result.

Is there any way to do this as we need to set the `level` tag to the "log level" on our side?

**Comment by goofansu** [comment]
Have the same problem, I want to set some information to warning level.

**Comment by ElPincheTopo** [comment]
Having the same problem

**Comment by cpnielsen** [comment]
We are looking to interface Sentry with alerting (OpsGenie and co) for some projects, and being able to set log level to `WARNING` at least is critical to making this useful.

**Comment by kamilogorek** [comment]
Moved to https://github.com/getsentry/raven-go/issues/237
