### ISSUE TITLE
Leaking goroutines.

### ISSUE THREAD

**Issue by malandrew** [getsentry/raven-go#90]
Merely including raven-go results in leaking goroutines. The culprit is this line:

https://github.com/getsentry/raven-go/blob/master/client.go#L307

main.go

```
package main
```

main_test.go

```
package main

import (
    "fmt"
    "os"
    "testing"

    _ "github.com/getsentry/raven-go"

    "github.com/uber/tchannel-go/testutils/goroutines"
)

func TestMain(m *testing.M) {
    exitCode := m.Run()
    if err := goroutines.IdentifyLeaks(nil); err != nil && exitCode == 0 {
        fmt.Fprintf(os.Stderr, "Found goroutine leaks on successful test run: %v", err)
        exitCode = 1
    }
    os.Exit(exitCode)
}
```

```
$ go test
PASS
Found goroutine leaks on successful test run: found unexpected goroutines:
[Goroutine 5 in state chan receive, with vendor/github.com/getsentry/raven-go.(*Client).worker on top of the stack:
goroutine 5 [chan receive]:
vendor/github.com/getsentry/raven-go.(*Client).worker(0xc8200be210)
    vendor/github.com/getsentry/raven-go/client.go:418 +0x60
created by vendor/github.com/getsentry/raven-go.newClient
    vendor/github.com/getsentry/raven-go/client.go:307 +0x193
]FAIL   test    0.913s
```

**Comment by mattrobenolt** [comment]
This should be relatively easy to make the worker goroutine lazy.

**Comment by malandrew** [comment]
@mattrobenolt That would be awesome. Thanks.

**Comment by tylrtrmbl** [comment]
From @mattrobenolt in #93:

> I think there's a difference between initializing a client with an empty DSN, vs you already having created one, and you want to stop using it. I don't think we should overload SetDSN here to also indicate "stop using an existing one".

And

> We can/should still make the goroutine start lazy. Though, I don't think we should do it inside SetDSN, since it's technically possible to call SetDSN multiple times, in which we'll start a new goroutine for each and likely cause other issues.

I think there's basically a problem of symmetry with the `DefaultClient`. I generally don't like a call to `Close` that can't be mapped to a single call to `Open`, for example.

Would you be opposed to requiring `Start` to be called to use the default client?

```go
func main() {
    sentry.Start()
    defer sentry.Close()
    // ...
}
```

More radical solution: remove the default client methods. I actually prefer the API with the methods sitting on a client object, and dislike the duplication. The creation of a client is a natural "yin" to our `Close` "yang".

I'm not sure the default client is necessary, and I don't see something similar to it in the Client API docs or the Python implementation (though I haven't looked closely at either recently).

**Comment by malandrew** [comment]
No objection to requiring Start() and a corresponding Close(). It's clean, explicit and feels like idiomatic go.

cc/ @prashantv

**Comment by mattrobenolt** [comment]
I completely disagree, and if we have to do `Start()`, we have a bad design, on top of breaking all existing usage for no gain. I think it should implicitly be ready to work, and we can make the worker goroutine start lazily. Sentry isn't a database where we need to open up a connection, then close it, and most users won't even need to explicitly call `Close()`, so this is just adding more complexity.

**Comment by mattrobenolt** [comment]
> I'm not sure the default client is necessary, and I don't see something similar to it in the Client API docs or the Python implementation (though I haven't looked closely at either recently).

We do. Rarely you need to create an instance of a `Client()` manually. We try to auto-initialize this for you as long as you set the proper configuration. The only problem here is the fact that the default client already begins to do work. I yanked this pattern out of the golang stdlib as well, for the http server library. It's generally convenient to have a singleton for our use cases.
